### ISSUE TITLE
Blending issues

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Content#103]
### Steps to reproduce
1. Run https://github.com/StarcounterApps/Content/commit/018952ab38ea36ae4880058ba491b4d67007f900 (current latest version on develop)
2. Run https://github.com/StarcounterApps/SignIn/commit/f4e3236811665c0cf0a1a38bb18f3bb97c983dfc (current latest version on develop)
3. Run https://github.com/StarcounterApps/Images/commit/66109266f9c28244d2c63df75d0c41fd2ffb639c (current latest version on develop)
4. Go to `http://localhost:8080/signin/signinuser` and log in (if you don't have a user, create an user using the button shown on that page)
5. Go to `http://localhost:8080/content/cms` and click on `Create`. Assign some value to `Url` and in the "Visual" editor write "444".  Click "Save", click "Go back".
6. Stop all apps.
7. In SignIn app add `Blender.MapUri<WebContent>("/images/partials/somethings-edit/{?}", null, x => x);` in a new lie around here: https://github.com/StarcounterApps/Images/blob/develop/src/Images/Api/MainHandlers.cs#L50
8. In Content app add `Blender.MapUri<WebContent>("/content/partials/cms/item/{?}");` in a new lie around here: https://github.com/StarcounterApps/Content/blob/develop/src/Content/Api/PartialHandlers.cs#L52
9. Run 3 apps again
10. From `http://localhost:8080/content/cms` click on "Edit" on the right of the content item that was previously created.

### Expected result
The view from the Image app should blend with the view from the Content app.
### Actual result
Error, having something like the following data:
```

{
  "_ver#c$": 0,
  "_ver#s": 0,
  "Content_0": {
    "Html": "/Content/views/MasterPage.html",
    "PartialUrl": "/content/partials/cms/item/Fv",
    "CurrentPage": {
      "Content_0": {
        "Html": "/Content/views/CmsItemPage.html",
        "WebContent": {
          "Url$": "/Fv",
          "Path$": "/FvPage.html",
          "Protected$": false,
          "Html$": "<p>444</p>",
          "Name$": "1",
          "Key": "Fv",
          "ParentPage$": null
        },
        "HasParent$": false,
        "AllPages": [
          {
            "Name": "4 (Fc)",
            "Key": "Fc"
          },
          {
            "Name": "dsada (Ly)",
            "Key": "Ly"
          },
          {
            "Name": "dsadas (Hw)",
            "Key": "Hw"
          },
          {
            "Name": "dsadas (LI)",
            "Key": "LI"
          },
          {
            "Name": "sada (LV)",
            "Key": "LV"
          },
          {
            "Name": "sdadas (LL)",
            "Key": "LL"
          },
          {
            "Name": "teeeeestv1 (I2)",
            "Key": "I2"
          }
        ],
        "Message$": "",
        "Alert": {
          "Type$": 0,
          "Target$": []
        },
        "SaveTrigger$": 0,
        "CancelTrigger$": 0,
        "RedirectUrl$": ""
      },
      "Images_0": {
        "Html": "<p>444</p>",
        "MaxFileSize": 10485760,
        "AllowedMimeTypes": [
          "image/gif",
          "image/jpeg",
          "image/png",
          "image/svg+xml",
          "video/mp4",
          "video/webm",
          "video/ogg"
        ],
        "Add$": 0,
        "Delete$": 0,
        "Save$": 0,
        "SessionId": "632205D4E826DCA200000010",
        "Illustrations": [],
        "Selected": {
          "Content": {
            "Html": "/Images/ViewModels/EditableContentPage.html",
            "Name$": "",
            "URL$": "",
            "Path$": "",
            "MimeType$": "",
            "MaxFileSize": 0,
            "AllowedMimeTypes": [],
            "SessionId": "632205D4E826DCA200000010",
            "Open$": 0,
            "Clear$": 0,
            "ContentPage": {
              "Html": "/Images/viewmodels/ContentPage.html",
              "MimeType": "",
              "Key": "",
              "URL": "",
              "Name": "",
              "IsVideo": false,
              "IsImage": false,
              "IsLightBoxVisible$": false,
              "ShowLightBox$": 0
            },
            "IsMobile$": false
          }
        }
      }
    }
  }
}
```

Please note how the value of `Content_0.CurrentPage.Images_0.Html` takes the value of `Content_0.CurrentPage.Content_0.WebContent.Html$` , but I don't think it should. This is the value that was saved at step 5.
##### Starcounter version 
SC 2.3.1.7166

@chrhol Could you please have a look?

**Comment by chrhol** [comment]
I have not run the steps yet, just checked the code, and I see that the `WebContent` class contains a `Html` property (which will contain the value added in the first steps).

If the instance of `Webcontent` is used as dataobject in images, the viewmodel property `Html` will be automatically bound to the dataobject by default, meaning that it will get `<p>444<p>` as value.

So if in images, `Html` should not be bound, we need to set `DefaultTemplate.Html.Bind = null;` in `EditableIllustrationsPage.json.cs` to specify that.

I will try this a bit later tonight and see if this is the case.

**Comment by Mihaiii** [comment]
Yes, I tried it and it works.
Thank you!
Could there be any unwanted side effects if I make that change in Image app?

**Comment by chrhol** [comment]
> Yes, I tried it and it works.
Thank you!
Could there be any unwanted side effects if I make that change in Image app?

I can't think of any. I think that the `Html` property should not be bound and that it was in this case was a side-effect. But with that said, I don't really know how the image app works in all cases, so don't take my answer as an absolute truth 😉

**Comment by Mihaiii** [comment]
Closing as fixed. Thanks!
