### ISSUE TITLE
Make it obvious for the user what "Uri", "Path", and "Protected" does

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Content#61]
Since this app will be used by non-technical users, it should be obvious what the different fields and options do. My suggestion is to have a helper text below each input field that appears on focus. 

I would also suggest renaming "Protected" to "Visibility".

**Comment by Mihaiii** [comment]
I don't think that having a "Visibility" checkbox since the end user might get the wrong idea of what it does. On the other hand, "Protected" is obscure enough to force the user to look it up in the docs :))).

"Private", maybe ?

**Comment by Mackiovello** [comment]
What about renaming it to "Visibility" and changing the input to radio buttons - "public", "admin only" etc.? 
That would be super clear.

**Comment by Mihaiii** [comment]
Do we keep the "Path" field, after all?

At the moment it work, but of course you'd have to use a URL like "/content/dynamic/content/views/NotFoundPage.html" so that autocomplete (what is typed in the `Url` field + "Page.html") isn't really useful.

**Comment by Mihaiii** [comment]
>  Do we keep the "Path" field after all?
Ping @warpech .

**Comment by warpech** [comment]
"Path" has the URI for the HTML value of the content.

I think that it is not required anymore to have two URIs: 

1. for the content
2. for the content's HTML

It should be the same URI but what your browser gets should depend on the request mimetype.

**Comment by Mihaiii** [comment]
Archiving as it applies to version 1, which is not used by anyone.
Please use version 2, which is much better. :)

Please reopen if it's still reproducible.
